// Date: 10/29/2014 4:04:08 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.fibonacci.FNAF.mob;

import com.fibonacci.FNAF.mob.entity.EntityChica;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Chica extends ModelBase
{
    //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer topF;
    ModelRenderer topB;
    ModelRenderer topL;
    ModelRenderer topR;
    ModelRenderer billT;
    ModelRenderer billB;

    public Chica()
    {
        textureWidth = 128;
        textureHeight = 64;

        head = new ModelRenderer(this, 0, 0);
        head.addBox(-4F, -8F, -4F, 8, 8, 8);
        head.setRotationPoint(0F, 0F, 0F);
        head.setTextureSize(128, 64);
        head.mirror = true;
        setRotation(head, 0F, 0F, 0F);
        body = new ModelRenderer(this, 16, 16);
        body.addBox(-4F, 0F, -2F, 8, 12, 4);
        body.setRotationPoint(0F, 0F, 0F);
        body.setTextureSize(128, 64);
        body.mirror = true;
        setRotation(body, 0F, 0F, 0F);
        rightarm = new ModelRenderer(this, 40, 16);
        rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
        rightarm.setRotationPoint(-5F, 2F, 0F);
        rightarm.setTextureSize(128, 64);
        rightarm.mirror = true;
        setRotation(rightarm, 0F, 0F, 0F);
        leftarm = new ModelRenderer(this, 40, 16);
        leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
        leftarm.setRotationPoint(5F, 2F, 0F);
        leftarm.setTextureSize(128, 64);
        leftarm.mirror = true;
        setRotation(leftarm, 0F, 0F, 0F);
        rightleg = new ModelRenderer(this, 0, 16);
        rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
        rightleg.setRotationPoint(-2F, 12F, 0F);
        rightleg.setTextureSize(128, 64);
        rightleg.mirror = true;
        setRotation(rightleg, 0F, 0F, 0F);
        leftleg = new ModelRenderer(this, 0, 16);
        leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
        leftleg.setRotationPoint(2F, 12F, 0F);
        leftleg.setTextureSize(128, 64);
        leftleg.mirror = true;
        setRotation(leftleg, 0F, 0F, 0F);
        topF = new ModelRenderer(this, 0, 0);
        topF.addBox(0F, 0F, 0F, 2, 3, 1);
        topF.setRotationPoint(-1F, -10F, -3F);
        topF.setTextureSize(128, 64);
        topF.mirror = true;
        setRotation(topF, 0.5576792F, 0F, 0F);
        topB = new ModelRenderer(this, 0, 0);
        topB.addBox(0F, 0F, 0F, 2, 3, 1);
        topB.setRotationPoint(-1F, -11F, 2F);
        topB.setTextureSize(128, 64);
        topB.mirror = true;
        setRotation(topB, -0.4461492F, 0F, 0F);
        topL = new ModelRenderer(this, 0, 0);
        topL.addBox(0F, 0F, 0F, 1, 4, 2);
        topL.setRotationPoint(2F, -11F, -1F);
        topL.setTextureSize(128, 64);
        topL.mirror = true;
        setRotation(topL, 0F, 0F, 0.5576792F);
        topR = new ModelRenderer(this, 0, 0);
        topR.addBox(0F, 0F, 0F, 1, 4, 2);
        topR.setRotationPoint(-3F, -10F, -1F);
        topR.setTextureSize(128, 64);
        topR.mirror = true;
        setRotation(topR, 0F, 0F, -0.5576851F);
        billT = new ModelRenderer(this, 0, 0);
        billT.addBox(0F, 0F, 0F, 4, 1, 2);
        billT.setRotationPoint(-2F, -5F, -6F);
        billT.setTextureSize(128, 64);
        billT.mirror = true;
        setRotation(billT, 0F, 0F, 0F);
        billB = new ModelRenderer(this, 0, 0);
        billB.addBox(0F, 0F, 0F, 4, 1, 2);
        billB.setRotationPoint(-2F, -3F, -6F);
        billB.setTextureSize(128, 64);
        billB.mirror = true;
        setRotation(billB, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        head.render(f5);
        body.render(f5);
        rightarm.render(f5);
        leftarm.render(f5);
        rightleg.render(f5);
        leftleg.render(f5);
        topF.render(f5);
        topB.render(f5);
        topL.render(f5);
        topR.render(f5);
        billT.render(f5);
        billB.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, EntityChica entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}

